stages:
  - test

before_script:
  - export CI_HOME="$( pwd )"
  - git submodule update --init --recursive
  - export SCRAM_ARCH="slc6_amd64_gcc530"
  - export CMSSW_VERSION="CMSSW_8_0_26_patch2"
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - cd ..
  - scramv1 project CMSSW $CMSSW_VERSION
  - cd $CMSSW_VERSION/src
  - eval `scramv1 runtime -sh`
  - cd $CI_HOME

test:
  stage: test
  tags:
    - cvmfs
  script:
    - cd $CMSSW_BASE/src
    - cp -r $CI_HOME DNN
    - source DNN/setup.sh
    - sed "s|numpy/arrayobject.h|/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/py2-numpy/1.11.1-ikhhed2/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h|g" DNN/Tensorflow/interface/Tensor.h > DNN/Tensorflow/interface/Tensor.h
    - scram b || exit ${?}
    - test_tftensor || exit ${?}
    - test_tfgraph
